# Generated by Django 2.0 on 2017-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcc_tu_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='node',
            name='type',
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_E',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_OP0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_OP1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_OP2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_args',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_body',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_bpos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_chain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_chan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_cnst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_cond',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_csts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_decl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_domn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_elts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_expr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_flds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_fn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_init',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_labl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_mngl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_prms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_ptd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_purp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_refd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_retn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_scpe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_unql',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_val',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_valu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='refs_vars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
