# Generated by Django 2.0 on 2017-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcc_tu_parser', '0002_auto_20170222_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='refs_argt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
