# Generated by Django 2.0 on 2017-02-26 16:02

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcc_tu_parser', '0004_auto_20170226_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcparams',
            name='function',
            field=compositefk.fields.CompositeForeignKey(default='', null_if_equal=[], on_delete=django.db.models.deletion.SET_NULL, related_name='func_param_header', to='gcc_tu_parser.Node', to_fields={'node_id': compositefk.fields.LocalFieldValue('function_decl'), 'source_file': compositefk.fields.LocalFieldValue('source_file')}),
        ),
        migrations.AddField(
            model_name='funcparams',
            name='parameters',
            field=compositefk.fields.CompositeForeignKey(default='', null_if_equal=[], on_delete=django.db.models.deletion.SET_NULL, related_name='func_params', to='gcc_tu_parser.Node', to_fields={'node_id': compositefk.fields.LocalFieldValue('function_param'), 'source_file': compositefk.fields.LocalFieldValue('source_file')}),
        ),


    ]
