# Generated by Django 2.0 on 2017-02-26 16:31

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcc_tu_parser', '0005_auto_20170226_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcparams',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gcc_tu_parser.SourceFile'),
        ),

    ]
