# Generated by Django 2.0 on 2017-02-28 09:31

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcc_tu_parser', '0007_auto_20170226_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_node', models.IntegerField()),
                ('item_pos', models.IntegerField()),
                ('value', models.IntegerField()),
                ('node_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='namedlist',
            name='node',
            field=compositefk.fields.CompositeForeignKey(default='', null_if_equal=[], on_delete=django.db.models.deletion.SET_NULL, related_name='list_header_header', to='gcc_tu_parser.Node', to_fields={'node_id': compositefk.fields.LocalFieldValue('starting_node'), 'source_file': compositefk.fields.LocalFieldValue('source_file')}),
        ),
        migrations.AddField(
            model_name='namedlist',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gcc_tu_parser.SourceFile'),
        ),
        migrations.AddField(
            model_name='namedlist',
            name='value_node',
            field=compositefk.fields.CompositeForeignKey(default='', null_if_equal=[], on_delete=django.db.models.deletion.SET_NULL, related_name='node_in_list', to='gcc_tu_parser.Node', to_fields={'node_id': compositefk.fields.LocalFieldValue('value'), 'source_file': compositefk.fields.LocalFieldValue('source_file')}),
        ),
        migrations.AlterUniqueTogether(
            name='namedlist',
            unique_together=set([('source_file', 'node_type', 'starting_node', 'item_pos', 'value')]),
        ),
    ]
