# Generated by Django 2.0 on 2017-02-28 09:40

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcc_tu_parser', '0008_auto_20170228_0931'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='funcparams',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='funcparams',
            name='function',
        ),
        migrations.RemoveField(
            model_name='funcparams',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='funcparams',
            name='source_file',
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(max_length=9),
        ),
        migrations.DeleteModel(
            name='FuncParams',
        ),
    ]
